version: '2.1'

services:

  validator:
    image: hyperledger/sawtooth-validator:0.8
    container_name: transfer-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawtooth admin keygen &&
          sawtooth keygen my_key &&
          sawtooth config genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawtooth admin genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  settings-tp:
    image: hyperledger/sawtooth-tp_settings:0.8
    container_name: transfer-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest_api:0.8
    container_name: transfer-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008 -vv

  shell:
    image: hyperledger/sawtooth-shell:0.8
    container_name: transfer-shell
    depends_on:
      - rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        tail -f /dev/null
      "
